### PR TITLE
Add Images against all widget on docs

### LINKED ISSUE #3095: Adding screenshots against different widget documentation
**Describe the Issue**
The current documentation does not have the corresponding screenshots.[Widget documentation](https://docs.opensrp.io/engineering/android-app/configuring/config-types/widget)

**Acceptance criteria**
All widgets should have the corresponding screenshots

### PR DESCRIPTION
**Pull request by brandy-kay**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3095

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — CHANGES_REQUESTED** [review]
please move the images to this folder, you can create a sub-folder in here to keep them organized, https://github.com/opensrp/fhircore/tree/main/static/img

**Review by pld — CHANGES_REQUESTED** [review]
I think the links are broken, this is what it looks like when rendered:

Screenshot 2024-02-26 at 12 50 33 PM

also, can you move these to a sub-folder to keep them organized, e.g. `static/img/config-types/`

**Comment by pld** [comment]
@rowo or @HenryRae can you please take a look at these rendered docs and give input on the layout? thank you!

**Comment by pld** [comment]
@brandy-kay thanks for fixing the links! The images render now, we'll have design take a look and see if they have any feedback before we merge it in

**Comment by HenryRae** [comment]
@pld could you please show how image is currently rendered? 

And more details on what we trying to solve/archive

**Comment by pld** [comment]
@HenryRae Roger said he showed you how to build the docs on your machine, any update on this?

**Comment by rowo** [comment]
@pld I don't know how to show @HenryRae how to build the docs on his machine as I had some issues getting the docs working on my new computer last week. So given that difficulty, I had to deprioritize it.

**Comment by SebaMutuku** [comment]
@HenryRae I can offer to show you how to build the docs. You can reach out whenever you are ready

**Comment by HenryRae** [comment]
I was able to setup docusaurus with @SebaMutuku  help, not sure what next now. Roger
cc: @pld

**Comment by pld** [comment]
> I was able to setup docusaurus with @SebaMutuku help, not sure what next now. cc: @pld

Great! Please take a look at the page `engineering > android-app > configuring > config-types > widget`, then sign-off on the layout there or request changes

**Comment by pld** [comment]
Specifically, please review the appearance of the images added on that page and if they look okay in terms of layout/aesthetics. If you would like anything changed, document it here. If it all looks okay, please sign off.

**Comment by pld** [comment]
@HenryRae is this good to go now?

**Comment by HenryRae** [comment]
@pld all looks good now

**Review by ellykits — APPROVED** [review]

**Pull request merged**
