### PR TITLE
Load QuestionnaireResponse from DB before launching Questionnaire

### LINKED ISSUE #1436: [Quest/eCBIS] - On Edit,  Household details Village Town is empty
**Describe the bug**
There is missing data for a family village or town in family details profile view, wrong labels on edit family details 

**Acceptance criteria**

- [x] 1. Click on a family from the family register 
- [x] 2. Click on the menu items 
- [x] 3. Select on the menu - Family details 
- [x] 4. The title of the page should be Edit Family details 
- [x] 5. All fields should be populated i.e Famil name, Household ID, and Village or Town
- [x] 6. Change the button text from Add family to Edit family 
- [x] 7. On save update family details 

**Screenshots**

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1436

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by FikriMilano** [comment]
We can merge this later after https://github.com/opensrp/fhircore/issues/1460 is closed

**Review by pld — APPROVED** [review]

**Review by pld — DISMISSED** [review]

**Comment by ellykits** [comment]
@FikriMilano Update this PR so it can be merged.

**Comment by dubdabasoduba** [comment]
Blocked by https://github.com/opensrp/fhircore/issues/1460

**Comment by FikriMilano** [comment]
Give me a moment, don't merge just yet

**Comment by FikriMilano** [comment]
Ok this is fine

**Comment by ellykits** [comment]
@FikriMilano Any updates on this PR?

**Comment by FikriMilano** [comment]
@ellykits I fixed the merge conflicts

**Comment by FikriMilano** [comment]
@ellykits this is ready

**Comment by dubdabasoduba** [comment]
@FikriMilano is this configurable? i.e can we load the data from the QUestionnaireResponse or the extracted resources?

**Comment by FikriMilano** [comment]
@dubdabasoduba it's not configurable.

If there is no QuestionnaireResponse in DB then generate QuestionnaireResponse.
DB first then generate.

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba it's not configurable.
> 
> If there is no QuestionnaireResponse in DB then generate QuestionnaireResponse. DB first then generate.

Not very sure how we generate a QR?  Is this by filling out the questionnaire?

**Comment by FikriMilano** [comment]
@dubdabasoduba 
We generate QR from extracted resources. So, yeah same thing.

**Review by ellykits — APPROVED** [review]
Fix merge conflict. Looks good!

**Review by pld — APPROVED** [review]

**Pull request merged**
