### PR TITLE
Update Maximum Heap Size From 6 to 10 GB

### PR DESCRIPTION
**Pull request by dubdabasoduba**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes [link to issue]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by qiarie — APPROVED** [review]

**Comment by ellykits** [comment]
@dubdabasoduba Did you try disabling minification in Quest? 

```
 isMinifyEnabled = false
 isShrinkResources = false
```

**Comment by ellykits** [comment]
I have investigated and noted the build runs out of memory with minification enabled. Can we disable the minification for now? I would want to test these changes locally first. The current workaround is to disable minification.

**Comment by ellykits** [comment]
Here is the PR for the workaround https://github.com/opensrp/fhircore/pull/3660

**Comment by dubdabasoduba** [comment]
> I have investigated and noted the build runs out of memory with minification enabled. Can we disable the minification for now? I would want to test these changes locally first. The current workaround is to disable minification.

@ellykits We can use the workaround right now but we do need minification added on the APKs by default for the future.

**Pull request merged**
