### PR TITLE
276| Enroll family and family member and anc e2e flow

### LINKED ISSUE #276: CHW/ANC SubTask - Enroll a family
- [ ] User can register a family. As part of family registration, a location is collected in order to add that family to the map? _(Need confirm if this is the way forward or if we want to register actual structures)_

3.5 days FTE + 20% buffer

SubTask 
- [ ] #520

### PR DESCRIPTION
**Pull request by maimoonak**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #276 

**Type**
Feature

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — APPROVED** [review]

**Comment by maimoonak** [comment]
@f-odhiambo mentioned that apk was crashing with him on pixel4a. Need to confirm the apk on mentioned device

**Comment by maimoonak** [comment]
App working confirmed.

**Review by pld — APPROVED** [review]
lgtm!

**Comment by owais** [comment]
@f-odhiambo I think you have the wrong Owais :)

**Comment by maimoonak** [comment]
This was done into another PR #547

**Pull request closed without merging**
