### PR TITLE
Filtering service points issue fixed

### PR DESCRIPTION
**Pull request by Aleem92**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

While filtering the register, if some filters are not selected but are mentioned in the dataQueries of nestedSearchResources, the non-selected filters are still included in the filtering query.

Fixes https://github.com/onaio/fhir-resources/pull/3459

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by dubdabasoduba** [comment]
@Aleem92 I tested this and it seems to work well however,  the Filter page resets every time you leave the page and go back to it. 

cc: @ellykits

**Comment by ellykits** [comment]
The reset was intentional @dubdabasoduba . Every time the questionnaire is launched, the previous filters are reset.

**Comment by dubdabasoduba** [comment]
> The reset was intentional @dubdabasoduba . Every time the questionnaire is launched, the previous filters are reset.

Why did we do it that way when we have the clear all function?

**Comment by Aleem92** [comment]
> @Aleem92 I tested this and it seems to work well when you select the visit status alone.
> 
> * If you select the flag alone even with the [fix](https://github.com/onaio/fhir-resources/pull/3459) that you and @hamza-vd made it doesn't seem to work well.
> * The forms reset every time you open it.
> 
> cc: @ellykits

@dubdabasoduba 

I have tested it by selecting only the flag filter, and it is working fine for me. Can you please share the steps to reproduce the issue? Perhaps I missed something during my testing.

As for the second point, it’s an existing issue and can be seen in the app using the main branch. Let me know if I should look into that as well!


https://github.com/user-attachments/assets/8d5dbab8-643e-44bf-908c-23041d353f7e

**Comment by dubdabasoduba** [comment]
@Aleem92 I have retested thing with the latest `main` on fhir-resources and it seems to work well

**Review by dubdabasoduba — APPROVED** [review]

**Pull request merged**
