### PR TITLE
Fix quest patient-registration dob calculation from age

### LINKED ISSUE #876: Quest : Patient registration with estimated age/dob not working
**Describe the bug**
On the quest app, one cannot successfully  register a patient 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Quest app
2. Click on Register new client 
3. Complete registration survey 
4. User not saved

**Expected behaviour**
1. On successfully save, I should be able to either view the client on the patient list or search and retrieve the user 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 12
 - Build number:SP1A.211105.002

**Additional context**

1. Update the registration questionnaire to have Date of birth selection default to date selection

### PR DESCRIPTION
**Pull request by ekigamba**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #876

**Type**
Choose one: Bug fix

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — COMMENTED** [review]
shouldn't these be loaded from the fhir server?

**Comment by ekigamba** [comment]
> shouldn't these be loaded from the fhir server?

They already are loaded on the FHIR server. We need to maintain some of the configurations/questionnaires on version control and use them to test also

**Comment by pld** [comment]
> > shouldn't these be loaded from the fhir server?
> 
> They already are loaded on the FHIR server. We need to store copies of the StructureMaps on version control

ok, are files in these folder automatically loaded into a test, or are you going to add new tests for these files to this pr?

also, it looks like the new files are in the eir app but they appear related to quest

**Comment by ekigamba** [comment]
> > > shouldn't these be loaded from the fhir server?
> > 
> > 
> > They already are loaded on the FHIR server. We need to store copies of the StructureMaps on version control
> 
> ok, are files in these folder automatically loaded into a test, or are you going to add new tests for these files to this pr?
> 
> also, it looks like the new files are in the eir app but they appear related to quest

Sorry, the main reason is storing the copies in version control. During development or update to the forms and extraction functionality, these can be used directly with the StructureMapUtilities class and the sample QR to manually test the authored StructureMap.
Currently, 
- We do not have functional tests with these files
- I don't have a good reason for keeping them in the eir module as opposed to having each in it's own module other than having them in a central location and being able to easily refer to them from the utilities class.
- We keep them in the tests package so that they are not bundled in the APK. It's also easier to manually verify that functionality works by running them in the tests package compared to having them in a separate project

**Comment by pld** [comment]
ok, thanks for the explanation, where are we storing the equivalent files for ANC?

**Comment by ekigamba** [comment]
> ok, thanks for the explanation, where are we storing the equivalent files for ANC?

They are also in the tests package for the `eir` module

**Comment by pld** [comment]
> > ok, thanks for the explanation, where are we storing the equivalent files for ANC?
> 
> They are also in the tests package for the `eir` module

can you send a link? looked for them [here](https://github.com/opensrp/fhircore/tree/main/android/eir/src/test/resources/structure-map-questionnaires)

**Comment by pld** [comment]
one thing I'm confused about, looking at that folder is the `patient-registration` and `quest-patient-registration` folders, is `patient-registration` for EIR? Is there a folder somewhere else for ANC?

Is the only reason they're in this location historical, or would moving these files around break something? I feel like there's a pretty good argument to put these outside the `android` folder altogether -- but that's a larger discussion.

If you can:
1. in this thread describe the location of the ANC vs EIR vs Quest registration forms and
2. separately open a new discussion issue, with your comments in this PR as a start, to address managing these types of static files

I think we're all set.

**Comment by ekigamba** [comment]
Yes, the `patient-registration` is for EIR. 

1. The location is purely historical at this point. The locations for:
- EIR StructureMap and corresponding files is `patient-registration`
- Quest StructureMap and corresponding files is `quest-patient-registration`
- ANC StructureMap and corresponding files for registration - I don't think we have this. However, we have the files for `vital-signs` which are [here](https://github.com/opensrp/fhircore/tree/main/android/eir/src/test/resources/structure-map-questionnaires)

2. I created the issue here https://github.com/opensrp/fhircore/discussions/917


We might not have a really reason or good structure while keeping them here, but I think that it provides more value for our(mostly my) workflow at this point in time to have these files in such kind of location until we have a better location that caters for the same reasons and provides better documentable structure. I believe the issue is the organization of the files. Additionally, given how early the usage of StructureMap and server configurations is, this is going to be a work in progress and will need more work to get to an agree-able point.

What do you think?

**Comment by pld** [comment]
I agree, no point worrying about location until we think it through further

**Review by pld — APPROVED** [review]

**Comment by Rkareko** [comment]
@ekigamba I tested registering a new patient with the option of entering the age. The app is crashing when the `save` button is clicked. On restarting the app the newly registered patient is visible on the register and the age displayed is correct.

The following is the exception logged when the app crashes 

```
2022-01-03 10:27:19.129 184-184/? A/libc: crash_dump helper failed to exec
2022-01-03 10:27:19.862 9590-9590/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 9590
    java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at org.smartregister.fhircore.engine.util.extension.QuestionnaireExtensionKt.cqfLibraryId(QuestionnaireExtension.kt:95)
        at org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireViewModel$extractAndSaveResources$1.invokeSuspend(QuestionnaireViewModel.kt:192)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2022-01-03 10:27:22.317 509-9929/? E/ActivityManager: ANR in org.smartregister.fhircore.quest (org.smartregister.fhircore.quest/org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity)
    PID: 9590
    Reason: Input dispatching timed out (98187b2 org.smartregister.fhircore.quest/org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity (server) is not responding. Waited 5003ms for FocusEvent(hasFocus=false))
    Parent: org.smartregister.fhircore.quest/org.smartregister.fhircore.engine.ui.questionnaire.QuestionnaireActivity
    Load: 1.44 / 1.41 / 1.76
    ----- Output from /proc/pressure/memory -----
    some avg10=0.27 avg60=0.18 avg300=0.29 total=14311055
    full avg10=0.01 avg60=0.04 avg300=0.05 total=3901393
    ----- End output from /proc/pressure/memory -----
```

**Comment by ekigamba** [comment]
@Rkareko This seems to be unrelated to this PR and was probably introduced from master in [this merge commit](https://github.com/opensrp/fhircore/pull/909/commits/112fc01f20526f88e203923bd604fc0e5bf589bc). I have created a separate issue here https://github.com/opensrp/fhircore/issues/919 to address this.

**Review by Rkareko — APPROVED** [review]

**Pull request merged**
