### PR TITLE
Cache paginated register data

### PR DESCRIPTION
**Pull request by ellykits**
Signed-off-by: Elly Kitoto <junkmailstoelly@gmail.com>

**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ndegwamartin** [comment]
@ellykits PR looks good, just a quick question, how does it handle freshly synced data from the server?

**Comment by ellykits** [comment]
Anytime sync will be triggered and it completes, the onSync function will
be called in the Fragment which will clear the cache. Moving through the
pages will refresh the data in the cache.

**Comment by ndegwamartin** [comment]
> Anytime sync will be triggered and it completes, the onSync function will be called in the Fragment which will clear the cache. Moving through the pages will refresh the data in the cache.
> […](#)

Noted. PR LGTM ✓

**Review by ndegwamartin — APPROVED** [review]

**Review by ndegwamartin — COMMENTED** [review]
@ellykits does it also update the cache for the local changes as well. e.g. when a new record is added or record is removed

**Comment by ellykits** [comment]
We will address that with the ON_CLOSE work flow for the questionnaire.
This event will be triggered say after submitting a questionnaire. We can
respond by reseting the cache for the register fragment.

**Pull request merged**
