### PR TITLE
Update UI from design QA feedback

### LINKED ISSUE #1961: [UX] App Configuration Page enhancement
**Describe the enhancement**
**Screenshot 1** 
image

1. Logo placement is off, should fill and centered as the design intended. Container properties should be followed
2. Input placeholder should be updated with the caption below. No need to use “Enter application ID” since this is used as the input label, and the caption “e.g ANC...” can stay or get moved into the placeholder.
3. Disabled button should have a grey label, the colors of the button and label should match as intended in the design
4. Can include app version here is necessary
5. space between the label and input field doesn’t match what the design intended.
check the space between the 2 items or the line height of the label to if matches with the design
NB: this applies to all input fields in the FHIR app

**Adjusted Designs**

image

**Screenshot 2** 
image

1. Logo placement when the keyboard shows up - The logo and content should push up to fit areas of the screen so that important actions and content aren’t hidden
2. Button and content placement when the keyboard shows up - The button should still show when the keyboard is launched

**Final mock**
image

### PR DESCRIPTION
**Pull request by ellykits**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #1961 #1962 #1963

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — APPROVED** [review]

**Review by pld — DISMISSED** [review]

**Review by pld — APPROVED** [review]

**Review by pld — APPROVED** [review]

**Comment by ellykits** [comment]
Noticed codecov is not reporting coverage for some test classes. Will fix this separately - no test data is reported however the lines are covered.

**Comment by pld** [comment]
K no worries fine to override for merge

**Comment by ellykits** [comment]
Noticed some changes breaking the app on the Pin Login screen, the keyboard remains hidden sometimes or disappears while entering the pin. Should be fixed before merging, Tagging with DNM for now.

**Comment by ellykits** [comment]
Issue resolved. Ready for review & merge.

**Comment by dubdabasoduba** [comment]
@ellykits this page looks very different. We are missing the log. The wording also seems off. Trying to find the mocks. 

Screenshot_20230124_143744

Can we update the Login page such that if the user enters the username and hits enter the cursor moves to the password, then if both the username and password are filled then we can shift the focus to the login button.

**Comment by ellykits** [comment]
This design was updated as requested by the Design team. The Logo and App names were removed on purpose to fulfill the requirements @HenryRae can comment on this.

**Comment by ellykits** [comment]
@dubdabasoduba Here is the link to [Figma](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?node-id=19491%3A127679&t=EwUrsTaQUkQjMvCZ-0)

**Comment by dubdabasoduba** [comment]
> This design was updated as requested by the Design team. The Logo and App names were removed on purpose to fulfill the requirements @HenryRae can comment on this.

Interesting. This looks very weird in terms of consistency. I might be wrong but I think all the login and pre-login pages should have the same look and feel.

**Comment by ellykits** [comment]
> * Can we update the Login page such that if the user enters the username and hits enter the cursor moves to the password, then if both the username and password are filled then we can shift the focus to the login button.
> * Pin on the "Set Pin" Should be in caps

These comments have been addressed @dubdabasoduba Re-run the app to test.

**Comment by HenryRae** [comment]
@dubdabasoduba the logo was removed on set PIN to reduce clutter on any sort of destruction, this also allows us to have more room for design to fully show when keyboard is open on smaller screens.
cc: @rowo any thoughts?

**Pull request merged**
