### PR TITLE
Tag resources with meta tags from Linkage resource

### LINKED ISSUE #3291: Adding a Related Entity Location Tag to resources linked to a Location or Entities linked to a location
**Describe the feature request.**
- Related Entity Location is a new sync strategy added on OpenSRP that gives the ability to sync data based on the location the entities are tied to.  
- In some cases the entities are directly linked to the locations via a List resource https://github.com/opensrp/fhircore/discussions/3034 
- The REL addition should always check if the List resource with the subject linked is available. If yes, it should then use the location defined on the List resource

**Acceptance criteria**
- [ ] Ability to add REL `meta.tag` to the resources generated for a subject linked to a location or the location itself. 

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

### PR DESCRIPTION
**Pull request by ellykits**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3291

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — DISMISSED** [review]

**Review by dubdabasoduba — CHANGES_REQUESTED** [review]
@ellykits This doesn't seem to work

Here is are sample resources from my tests

## Questionnaire Response
```json
{
  "resourceType": "QuestionnaireResponse",
  "id": "166d0349-bff0-4ec1-8b7c-1dd6fe4e96c2",
  "meta": {
    "lastUpdated": "2024-06-05T10:17:06.061+03:00",
    "tag": [
      {
        "system" : "https://smartregister.org/care-team-tag-id",
        "code"   : "4ddd4157-921b-4c65-820c-161b6e845011"      ,
        "display": "Practitioner CareTeam"
      },
      {
        "system" : "https://smartregister.org/location-tag-id",
        "code"   : "f15ff8ab-9475-4356-8363-7f518fdd66ce"     ,
        "display": "Practitioner Location"
      },
      {
        "system" : "https://smartregister.org/organisation-tag-id",
        "code"   : "d0882d3a-f35a-43cf-9d43-2ea9f9793e24"         ,
        "display": "Practitioner Organization"
      },
      {
        "system" : "https://smartregister.org/practitioner-tag-id",
        "code"   : "ab929110-6918-4d0b-8961-13cce4d5c76b"         ,
        "display": "Practitioner"
      },
      {
        "system" : "https://smartregister.org/app-version",
        "code"   : "2.0.0-eusm"                           ,
        "display": "Application Version"
      }
    ]
  },
  "contained": [
    {
      "resourceType": "List",
      "id": "c2535ef0-daba-4000-b6b1-4cea7fccfc2f",
      "status": "current",
      "mode": "working",
      "title": "GeneratedResourcesList",
      "date": "2024-06-05T10:17:05+03:00",
      "entry": [
        {
          "deleted": false,
          "date": "2024-06-05T10:17:05+03:00",
          "item": {
            "reference": "Encounter/ea925d53-fbd0-4f96-a22d-f87985aa8479"
          }
        },
        {
          "deleted": false,
          "date": "2024-06-05T10:17:05+03:00",
          "item": {
            "reference": "Encounter/1c7fafc9-28b7-47e4-b45c-c47b6896e97a"
          }
        },
        {
          "deleted": false,
          "date": "2024-06-05T10:17:05+03:00",
          "item": {
            "reference": "Observation/20883012-ceb2-45b4-be9a-a7166fcf723e"
          }
        },
        {
          "deleted": false,
          "date": "2024-06-05T10:17:05+03:00",
          "item": {
            "reference": "Observation/1d47ff6a-2eb2-44c9-86b5-872b6c24f085"
          }
        },
        {
          "deleted": false,
          "date": "2024-06-05T10:17:05+03:00",
          "item": {
            "reference": "Observation/69bc54cf-4692-416d-94a8-42e8b58c40f4"
          }
        },
        {
          "deleted": false,
          "date": "2024-06-05T10:17:05+03:00",
          "item": {
            "reference": "Observation/2d8ecf51-8b12-40f0-8c17-db73457f3f5a"
          }
        }
      ]
    }
  ],
  "questionnaire": "Questionnaire/97f117a8-2a05-45c9-c49d-77d0ae5feaea",
  "status": "completed",
  "subject": {"reference": "Location/c20fa259-1beb-42ad-b186-b8a7d18fc622"},
  "authored": "2024-06-05T10:17:00+03:00",
  "author": {"reference": "Practitioner/ab929110-6918-4d0b-8961-13cce4d5c76b"},
  "item": [
    {
      "linkId": "874ba664-2eba-4694-b295-9dca1190c1f9",
      "text": "Are there other UNICEF-supplied products at the service point which require action (ask the End User)?",
      "answer": [
        {
          "valueCoding": {
            "id": "e3f5cc32-2ba9-484f-9916-a1ec6d36822c",
            "system": "urn:uuid:50def0e2-0077-4a3e-fbc9-1f5619417864",
            "code": "yes",
            "display": "Yes",
            "_display": {
              "extension": [
                {
                  "url": "http://hl7.org/fhir/StructureDefinition/translation",
                  "extension": [
                    {"url": "lang", "valueCode": "fr"}      ,
                    {"url": "content", "valueString": "Oui"}
                  ]
                }
              ]
            }
          }
        }
      ]
    },
    {
      "linkId": "92c1a272-ad39-4929-817c-9e134c4d9a62",
      "text": "Please describe:",
      "answer": [
        {"valueString": "Checking"}
      ]
    },
    {
      "linkId": "66ef491a-1317-4c12-88ad-839981bc6e54",
      "text": "Did the End User mention any products that the service point needs (ask the End User)?",
      "answer": [
        {
          "valueCoding": {
            "id": "f845d6e1-9652-4253-df67-4089eb4b4ba4",
            "system": "urn:uuid:c45e0d09-539f-4598-8015-3ed803a156d0",
            "code": "no",
            "display": "No",
            "_display": {
              "extension": [
                {
                  "url": "http://hl7.org/fhir/StructureDefinition/translation",
                  "extension": [
                    {"url": "lang", "valueCode": "fr"}      ,
                    {"url": "content", "valueString": "Non"}
                  ]
                }
              ]
            }
          }
        }
      ]
    },
    {
      "linkId": "c6a29b5e-14e3-4921-9528-d8ab094a7308",
      "text": "Is the service point overall in good working order?",
      "answer": [
        {
          "valueCoding": {
            "id": "7ede0efb-cff4-433f-9da7-733c12964f57",
            "system": "urn:uuid:547f95c4-325f-43cf-8173-9d88abc0fcd9",
            "code": "yes",
            "display": "Yes",
            "_display": {
              "extension": [
                {
                  "url": "http://hl7.org/fhir/StructureDefinition/translation",
                  "extension": [
                    {"url": "lang", "valueCode": "fr"}      ,
                    {"url": "content", "valueString": "Oui"}
                  ]
                }
              ]
            }
          }
        }
      ]
    },
    {"linkId": "visit-encounter-id"},
    {
      "linkId": "close-visit-encounter",
      "answer": [
        {"valueString": "no"}
      ]
    },
    {"linkId": "flag-resource-id"}
  ]
}
```

## Encounter

```json
{
  "resourceType": "Encounter",
  "id": "ea925d53-fbd0-4f96-a22d-f87985aa8479",
  "meta": {
    "lastUpdated": "2024-06-05T10:17:05.759+03:00",
    "tag": [
      {
        "system" : "https://smartregister.org/care-team-tag-id",
        "code"   : "4ddd4157-921b-4c65-820c-161b6e845011"      ,
        "display": "Practitioner CareTeam"
      },
      {
        "system" : "https://smartregister.org/location-tag-id",
        "code"   : "f15ff8ab-9475-4356-8363-7f518fdd66ce"     ,
        "display": "Practitioner Location"
      },
      {
        "system" : "https://smartregister.org/organisation-tag-id",
        "code"   : "d0882d3a-f35a-43cf-9d43-2ea9f9793e24"         ,
        "display": "Practitioner Organization"
      },
      {
        "system" : "https://smartregister.org/practitioner-tag-id",
        "code"   : "ab929110-6918-4d0b-8961-13cce4d5c76b"         ,
        "display": "Practitioner"
      },
      {
        "system" : "https://smartregister.org/app-version",
        "code"   : "2.0.0-eusm"                           ,
        "display": "Application Version"
      }
    ]
  },
  "identifier": [
    {"use": "usual", "value": "0ab0e4d3-6da8-4413-83d7-4f575f35143b"}
  ],
  "status": "finished",
  "class": {
    "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code"  : "OBSENC"
  },
  "type": [
    {
      "coding": [
        {
          "system" : "http://snomed.info/sct",
          "code"   : "SPCHECK"               ,
          "display": "Service Point Check"
        }
      ],
      "text": "Service Point Check"
    }
  ],
  "priority": {
    "coding": [
      {
        "system" : "http://terminology.hl7.org/ValueSet/v3-ActPriority",
        "code"   : "EL"                                                ,
        "display": "elective"
      }
    ],
    "text": "elective"
  },
  "participant": [
    {
      "individual": {
        "reference": "Practitioner/ab929110-6918-4d0b-8961-13cce4d5c76b"
      }
    }
  ],
  "period": {
    "start": "2024-06-05T10:17:05+03:00",
    "end"  : "2024-06-05T10:17:05+03:00"
  },
  "reasonCode": [
    {
      "coding": [
        {
          "system" : "https://smartregister.org/",
          "code"   : "SPCHECK"                   ,
          "display": "Service Point Check"
        }
      ],
      "text": "Service Point Check"
    }
  ],
  "location": [
    {
      "location": {
        "reference": "Location/c20fa259-1beb-42ad-b186-b8a7d18fc622"
      },
      "status": "active"
    }
  ],
  "serviceProvider": {
    "reference": "Organization/d0882d3a-f35a-43cf-9d43-2ea9f9793e24"
  },
  "partOf": {"reference": "Encounter/1c7fafc9-28b7-47e4-b45c-c47b6896e97a"}
}
```

## Observation
```json
{
  "resourceType": "Observation",
  "id": "20883012-ceb2-45b4-be9a-a7166fcf723e",
  "meta": {
    "lastUpdated": "2024-06-05T10:17:05.876+03:00",
    "tag": [
      {
        "system": "https://smartregister.org/care-team-tag-id",
        "code": "4ddd4157-921b-4c65-820c-161b6e845011",
        "display": "Practitioner CareTeam"
      },
      {
        "system": "https://smartregister.org/location-tag-id",
        "code": "f15ff8ab-9475-4356-8363-7f518fdd66ce",
        "display": "Practitioner Location"
      },
      {
        "system": "https://smartregister.org/organisation-tag-id",
        "code": "d0882d3a-f35a-43cf-9d43-2ea9f9793e24",
        "display": "Practitioner Organization"
      },
      {
        "system": "https://smartregister.org/practitioner-tag-id",
        "code": "ab929110-6918-4d0b-8961-13cce4d5c76b",
        "display": "Practitioner"
      },
      {
        "system": "https://smartregister.org/app-version",
        "code": "2.0.0-eusm",
        "display": "Application Version"
      }
    ]
  },
  "identifier": [
    {
      "use": "usual",
      "value": "90ce58a6-2f7c-4301-82fa-f170467abd35"
    }
  ],
  "status": "final",
  "category": [
    {
      "coding": [
        {
          "system": "https://smartregister.org/",
          "code": "SPCHECK",
          "display": "Service Point Check"
        }
      ],
      "text": "Service Point Check"
    }
  ],
  "code": {
    "coding": [
      {
        "system": "https://smartregister.org/",
        "code": "65757934",
        "display": "Service Point Other Products Needed Check"
      }
    ],
    "text": "Service Point Other Products Needed Check"
  },
  "subject": {
    "reference": "Location/c20fa259-1beb-42ad-b186-b8a7d18fc622"
  },
  "encounter": {
    "reference": "Encounter/ea925d53-fbd0-4f96-a22d-f87985aa8479"
  },
  "effectivePeriod": {
    "start": "2024-06-05T10:17:05+03:00",
    "end": "2024-06-05T10:17:05+03:00"
  },
  "performer": [
    {
      "reference": "Practitioner/ab929110-6918-4d0b-8961-13cce4d5c76b"
    }
  ],
  "valueCodeableConcept": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "373066001",
        "display": "Yes (qualifier value)"
      }
    ],
    "text": "Yes (qualifier value)"
  },
  "note": [
    {
      "time": "2024-06-05T10:17:05+03:00",
      "text": "Checking"
    }
  ]
}
```

**Comment by dubdabasoduba** [comment]
## Configs
Screenshot 2024-06-06 at 15 09 16

**Comment by pld** [comment]
@dubdabasoduba how's this looking now?

**Comment by ellykits** [comment]
I reproduced the bug will be pushing the fix in a few @dubdabasoduba

**Comment by ellykits** [comment]
Issue resolved. @dubdabasoduba Re-test.

**Comment by dubdabasoduba** [comment]
@ellykits REL tags are now added but we seem to have multiple tags

```json
{
  "resourceType": "Observation",
  "id": "3669902a-55fa-4751-8a42-bab836ce2b5b",
  "meta": {
    "lastUpdated": "2024-06-11T20:43:58.698+03:00",
    "tag": [
      {
        "system" : "https://smartregister.org/related-entity-location-tag-id",
        "code"   : "20bef46f-b5f2-490f-beca-d9fa6205be06"                    ,
        "display": "Related Entity Location"
      },
      {
        "system" : "https://smartregister.org/related-entity-location-tag-id",
        "code"   : "20bef46f-b5f2-490f-beca-d9fa6205be06"                    ,
        "display": "Related Entity Location"
      },
      {
        "system" : "https://smartregister.org/related-entity-location-tag-id",
        "display": "Related Entity Location"
      },
      {
        "system" : "https://smartregister.org/care-team-tag-id",
        "code"   : "4ddd4157-921b-4c65-820c-161b6e845011"      ,
        "display": "Practitioner CareTeam"
      },
      {
        "system" : "https://smartregister.org/location-tag-id",
        "code"   : "f15ff8ab-9475-4356-8363-7f518fdd66ce"     ,
        "display": "Practitioner Location"
      },
      {
        "system" : "https://smartregister.org/organisation-tag-id",
        "code"   : "d0882d3a-f35a-43cf-9d43-2ea9f9793e24"         ,
        "display": "Practitioner Organization"
      },
      {
        "system" : "https://smartregister.org/practitioner-tag-id",
        "code"   : "ab929110-6918-4d0b-8961-13cce4d5c76b"         ,
        "display": "Practitioner"
      },
      {
        "system" : "https://smartregister.org/app-version",
        "code"   : "2.0.0-eusm"                           ,
        "display": "Application Version"
      }
    ]
  },
  "identifier": [
    {"use": "usual", "value": "b5550f3b-c32a-4b9f-b112-48ad6c4b1ec7"}
  ],
  "status": "final",
  "category": [
    {
      "coding": [
        {
          "system" : "http://smartregister.org/",
          "code"   : "PRODCHECK"                ,
          "display": "Product Check"
        }
      ],
      "text": "Product Check"
    }
  ],
  "code": {
    "coding": [
      {
        "system" : "http://snomed.info/sct",
        "code"   : "issue_details"         ,
        "display": "Issue Details"
      }
    ],
    "text": "Issue Details"
  },
  "subject": {"reference": "Group/e44e26d0-1f7a-41d6-aa57-99c5712ddd66"},
  "encounter": {"reference": "Encounter/e0c25150-c01f-44f8-a6ef-faed8a6e3ec6"},
  "effectivePeriod": {
    "start": "2024-06-11T20:43:58+03:00",
    "end"  : "2024-06-11T20:43:58+03:00"
  }
}
```

**Comment by ellykits** [comment]
Nice catch @dubdabasoduba. Issue resolved.

**Comment by dubdabasoduba** [comment]
@ellykits I tested this again. I think we missed and edge case

```json
{"resourceType":"Encounter","id":"ded607e4-805e-46d7-94c3-f1e68e006d3d","meta":{"lastUpdated":"2024-06-12T15:41:44.409+03:00","tag":[{"system":"https://smartregister.org/care-team-tag-id","code":"4ddd4157-921b-4c65-820c-161b6e845011","display":"Practitioner CareTeam"},{"system":"https://smartregister.org/location-tag-id","code":"f15ff8ab-9475-4356-8363-7f518fdd66ce","display":"Practitioner Location"},{"system":"https://smartregister.org/organisation-tag-id","code":"d0882d3a-f35a-43cf-9d43-2ea9f9793e24","display":"Practitioner Organization"},{"system":"https://smartregister.org/practitioner-tag-id","code":"ab929110-6918-4d0b-8961-13cce4d5c76b","display":"Practitioner"},{"system":"https://smartregister.org/app-version","code":"2.0.0-eusm","display":"Application Version"}]},"identifier":[{"use":"usual","value":"65339deb-9558-4530-bf85-7bca9d7c3703"}],"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"OBSENC"},"type":[{"coding":[{"system":"http://smartregister.org/","code":"CNBEN","display":"Consult Beneficiaries Visit"}],"text":"Consult Beneficiaries Visit"}],"priority":{"coding":[{"system":"http://terminology.hl7.org/ValueSet/v3-ActPriority","code":"EL","display":"elective"}],"text":"elective"},"participant":[{"individual":{"reference":"Practitioner/ab929110-6918-4d0b-8961-13cce4d5c76b"}}],"period":{"start":"2024-06-12T15:41:44+03:00","end":"2024-06-12T15:41:44+03:00"},"reasonCode":[{"coding":[{"system":"https://smartregister.org/","code":"CNBEN","display":"Consult Beneficiaries Visit"}],"text":"Consult Beneficiaries Visit"}],"location":[{"location":{"reference":"Location/5c70635b-286d-4a65-8275-3169554b7ee8"},"status":"active"}],"serviceProvider":{"reference":"Organization/d0882d3a-f35a-43cf-9d43-2ea9f9793e24"},"partOf":{"reference":"Encounter/8b44e438-3179-4f01-96b8-6a9821e7e19d"}}
```

In the case where the LIST resource is not available but the `resourceIdentifier` and `resourceType` point to a location we should also add the REL as the location ID found on the `resourceIdentifier`


This will cater for actions performed directly for the location. The LIST resource will only be available for locations with other items assigned to them

Consult benficiaries

**Comment by dubdabasoduba** [comment]
@ellykits works like a charm

**Review by dubdabasoduba — DISMISSED** [review]

**Pull request merged**
