### PR TITLE
Upgrade FHIR SDK dependencies ⬆️

### LINKED ISSUE #3421: Dependencies Upgrade + Migration
**Describe the Issue**

- [x] Publish latest FHIR SDK Artifacts
- [x] Migrate FHIR Core

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3421 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by f-odhiambo — APPROVED** [review]
This PR works as expected for the use cases I have tested

**Review by f-odhiambo — CHANGES_REQUESTED** [review]
CQL works in ZEIR but as Measure Reporting is broken 

```java
Exception thrown with measureUrl: https://fhir.labs.smartregister.org/fhir/Measure/ClinicAttendance   
```
```                                                                                      
java.lang.NullPointerException: id is required on all Elements of type: Measure.group.population
```

KM is looking for us to provide an ID as part of the params 

```kotlin
  /** Loads resources from IGs listed in dependencies. */
  suspend fun loadResources(
    resourceType: String,
    url: String? = null,
    id: String? = null,
    name: String? = null,
    version: String? = null,
  ):
```

**Comment by f-odhiambo** [comment]
@dubdabasoduba @owais-vd Can we also test this on $apply ? Aug 5th 
CC @ndegwamartin

**Comment by ndegwamartin** [comment]
> CQL works in ZEIR but as Measure Reporting is broken
> 
> ```java
> Exception thrown with measureUrl: https://fhir.labs.smartregister.org/fhir/Measure/ClinicAttendance   
> ```
> 
> ```
> java.lang.NullPointerException: id is required on all Elements of type: Measure.group.population
> ```
> 
> KM is looking for us to provide an ID as part of the params
> 
> ```kotlin
>   /** Loads resources from IGs listed in dependencies. */
>   suspend fun loadResources(
>     resourceType: String,
>     url: String? = null,
>     id: String? = null,
>     name: String? = null,
>     version: String? = null,
>   ):
> ```

From my investigations it appears that the group population id is now mandatory so you will need to include it in your measure jsons - [see this sample from the FHIR SDK](https://github.com/google/android-fhir/blame/603792f4e865ba3c736565d40672eda3a587ad97/workflow/sampledata/smart-imm/ig/Measure-IMMZIND05.json#L42)

I could not find any HL7 FHIR documentation to back it as a required field but I did come across this extension in some IG which introduces it as an extension - https://build.fhir.org/ig/HL7/davinci-deqm/StructureDefinition-extension-populationReference.html

Not sure why [the clinical reasoning library has made it mandatory](https://github.com/cqframework/clinical-reasoning/blob/03d6a92340a0c916abe1181182e28a5c5c41af99/cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureDefBuilder.java#L76).

**Comment by ellykits** [comment]
There are changes made to the [FhirEngineImpl](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt) methods/functions. We will no longer need the IO dispatcher in the default repository class functions.

**Review by f-odhiambo — APPROVED** [review]
LGTM

**Pull request merged**
