### PR TITLE
Filter register data by selected related entity locations

### LINKED ISSUE #3290: Filter the register results based on the Location selection on the multi-select widget
**Describe the feature request.**
- The [multi-select](https://github.com/opensrp/fhircore/issues/3068) widget allows users to control the data they download to the app. 
- We would like to update the functionality to filter a register based on the location selection.  This would help hide data that a user doesn't need at that instance. 

**Acceptance criteria**
- [ ] Only show locations/points with in the selected jurisdictions on the multi-select widget

### PR DESCRIPTION
**Pull request by ellykits**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3290

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — DISMISSED** [review]

**Review by pld — COMMENTED** [review]
do we need to add any docs wrt how to configure this?

**Comment by ellykits** [comment]
Yes we need to document this.

**Review by dubdabasoduba — CHANGES_REQUESTED** [review]
This seems to fail, please check attach screenshot

**Comment by ellykits** [comment]
@dubdabasoduba Can you re-test this?

**Review by dubdabasoduba — CHANGES_REQUESTED** [review]
@ellykits This still seems to fail

https://github.com/opensrp/fhircore/assets/4817531/f5b9c119-6b59-49ab-a724-f66219702f75

**Comment by ellykits** [comment]
Did you re-open the register?

**Comment by ellykits** [comment]
Screenshot_1718091374

**Comment by ellykits** [comment]
I was able to reproduce the issue @dubdabasoduba. Fixed it.

**Comment by pld** [comment]
@dubdabasoduba can you take a look at this?

**Review by dubdabasoduba — APPROVED** [review]

**Comment by dubdabasoduba** [comment]
@ellykits  @pld this works like a charm
https://github.com/opensrp/fhircore/assets/4817531/3a6d80e4-82ad-47c4-8b6e-27ccd88f58f7

**Pull request merged**
