### PR TITLE
Add `nothing` app workflow

### PR DESCRIPTION
**Pull request by FikriMilano**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Change:
Add `NOTHING` as new ApplicationWorkflow.

Why:
Useful when the ApplicationWorkflow is configurable, when there's certain use case where if the user clicks a button, it does nothing.

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ellykits** [comment]
I do not understand the use case for this @FikriMilano. How will this be used?

**Comment by FikriMilano** [comment]
say @ellykits can we simply declare a `null` in rules? will that make the button does nothing when clicked?
```
{
  "name": "onClick",
  "condition": "true",
  "priority": 2,
  "actions": [
    "data.put('onClick', data.get('taskCode').equals('029') ? 'LAUNCH_PROFILE' : null)"
  ]
}
```

**Comment by FikriMilano** [comment]
Based on this line, it should be ok to declare a null
https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensions.kt#L103

**Comment by ellykits** [comment]
> Say @ellykits can we simply declare a `null` in rules? will that make the button does nothing when clicked? This new workflow was meant to replace `null` value as I thought we can't declare one while inside a rule.
> 
> ```
> {
>   "name": "onClick",
>   "condition": "true",
>   "priority": 2,
>   "actions": [
>     "data.put('onClick', data.get('taskCode').equals('029') ? 'LAUNCH_PROFILE' : null)"
>   ]
> }
> ```

You can use the rule condition instead. In your case, the rule should only be executed if the task code is '029'. Re-write the rule to: 

```json
{
  "name": "onclickAction",
  "condition": "data.get('taskCode').equals('029')",
  "priority": 2,
  "actions": [
    "data.put('onclickAction', 'LAUNCH_PROFILE')"
  ]
}
```

**Comment by ellykits** [comment]
Alternatively, you can use the `clickable` attribute that accepts a boolean from an executed rule. @FikriMilano. If the check is not performed before a click action for your widget, could you implement it? Theoretically, it should work for all supported widgets.

**Comment by ellykits** [comment]
I'm closing this, use the suggestions in the comments. Feel free to re-open this if the suggestions do not work @FikriMilano.

**Pull request closed without merging**
