### PR TITLE
Render profile UI incrementally

### LINKED ISSUE #2165: Render profile view in stages
**Describe the Issue**
Render the profile view in stages so that the page is not left blank for a period of time. The page will be rendered as soon as it receives data.

- Split loading and rendering of data so that the demographic data is shown immediately it's rendered. 
- Split the rendering of list items in the profile page so that each list item is fetched, run through the rules engine to calculate the values to be shown and then rendered immediately before moving to the item. This assumes that each list items has related resources that take time to load thus the difference in UX when rendered individually given that the primary list of resources is loaded from a single database query

### PR DESCRIPTION
**Pull request by ellykits**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2165 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 

**Code Reviewer Checklist**
- [x] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [x] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [x] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [x] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ellykits** [comment]
@FikriMilano Requested your review to confirm the deleted unused code is in order.

**Comment by ndegwamartin** [comment]
@ellykits looks good to me, please consider adding the enhancement to the change log

**Comment by ndegwamartin** [comment]
Later we might want to in collaboration with the design team see if we want to add some minimal animation transitions for when the rows appear

**Comment by ellykits** [comment]
For the animation I can add a [slideInVertically](https://developer.android.com/jetpack/compose/animation/composables-modifiers#crossfade) animation for now. Easier to do with Compose.

**Pull request merged**
