### PR TITLE
224 | Vaccination status styling on patient list

### LINKED ISSUE #224: Styling of vaccine status in patient list and profile view
Add styling to the patient list for the vaccine status based on the provided mock attached here. 

Acceptance criteria 
- [x] When fully vaccinate show _A green vaccinated text with a check-tick on top_
- [x] On a partially vaccinated i.e show _Greyed out label Vaiine 1 with the date received at the bottom of it_ 
- [x] When overdue show _Red Label with Overdue text_ 
- [x] When not vaccinated show _a Blue text - Record vaccine_ 

image
image

### PR DESCRIPTION
**Pull request by maimoonak**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #224 

**Type**
Choose one: (Feature) 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by maimoonak** [comment]
Screenshot from 2021-06-15 15-08-10

**Comment by ndegwamartin** [comment]
Marking this with a DNM for now. Borrows a lot from the `covaxx-demo` code we need to refactor.

**Comment by pld** [comment]
after rebase is this mergeable now?

**Comment by pld** [comment]
@maimoonak not high priority, but worth seeing if this can go in now after a rebase before it gets farther away from main

**Comment by maimoonak** [comment]
the rebasing or merging over main seems to be almost impossible on this branch. Since now required changes are small and include styling only hence closing this PR in favor of https://github.com/opensrp/fhircore/pull/413.

**Pull request closed without merging**
