### PR TITLE
Fix UI tests for debugNonProxy build

### LINKED ISSUE #2885: Enable UI tests on debugNonProxy build variants
Currenty, if you are on a `debugNonProxy` build variant you can't run UI tests. The `androidTest` folder pictured below disappears and running UI tests is disabled.
image

A quick fix to enable testing is to add this into the `build.gradle: quest`

`
android {
   testBuildType = "debugNonProxy"
}
`

However, this disables UI testing for the debug variants. Therefore we likely need an if else statement to enforce testing on both build variants.

### PR DESCRIPTION
**Pull request by LZRS**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2885 

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ellykits** [comment]
Good one. :+1:

**Comment by ellykits** [comment]
@LZRS How is this PR related to the issue linked to it? Replacing navController mocks is quite unrelated. There were some updates as well on removing FHIREngine mocks. Looks like we may need a new issue for this PR. This PR also replaces the dispatcher provider used in tests. That can be addressed separately as well, we actually need to refactor the deprecated `TestDispatcherCoroutine` by migrating to the latest library [see migration docs on coroutine test ](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md)

**Comment by LZRS** [comment]
> @LZRS How is this PR related to the issue linked to it? Replacing navController mocks is quite unrelated. There were some updates as well on removing FHIREngine mocks. Looks like we may need a new issue for this PR. This PR also replaces the dispatcher provider used in tests. That can be addressed separately as well, we actually need to refactor the deprecated `TestDispatcherCoroutine` by migrating to the latest library [see migration docs on coroutine test ](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md)

Yeah, you're right. They're mostly addressing issues I experienced while working on the issue attached, I'll add relevant issues and attach

**Comment by LZRS** [comment]
Moved the unrelated changes to this PR https://github.com/opensrp/fhircore/pull/2908

**Comment by LZRS** [comment]
Closing this, since most projects will be moving to FHIR gateway

**Pull request closed without merging**
