### PR TITLE
Refactor to Rename Quest Module To OpenSRP 

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

 Quest Module Rename To OpenSRP 

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [x] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ndegwamartin** [comment]
Marking this as Draft until we resolve on the base package name we want for the product. Do we still want to have **Fhircore** in the signature? cc @pld 

Right now with this refactor it looks like this:
- Generic OpenSRP APK - `org.smartregister.fhircore.opensrp`
- eCBIS APK - `org.smartregister.fhircore.opensrp.ecbis`
- ZEIR APK - `org.smartregister.fhircore.opensrp.zeir`

**Comment by ndegwamartin** [comment]
> Marking this as Draft until we resolve on the base package name we want for the product. Do we still want to have **Fhircore** in the signature? cc @pld
> 
> Right now with this refactor it looks like this:
> 
> * Generic OpenSRP APK - `org.smartregister.fhircore.opensrp`
> * eCBIS APK - `org.smartregister.fhircore.opensrp.ecbis`
> * ZEIR APK - `org.smartregister.fhircore.opensrp.zeir`

**Note**: Once the APK is distributed manually or on _Playstore_ we can't change it unless we force all user to perform a fresh install via a different link

**Comment by pld** [comment]
I think we miscommunicated here, let's talk before we make any further changes to be sure we're on the same page.

The main change I was interested in is the name of the APK that we generate as the generic APK, calling that OpenSRP vs Quest. For the internal code package names, I don't have a strong opinion on what that's called, I'm fine keeping it as it is in current main.

**Comment by ellykits** [comment]
> The main change I was interested in is the name of the APK that we generate as the generic APK, calling that OpenSRP vs Quest. For the internal code package names, I don't have a strong opinion on what that's called, I'm fine keeping it as it is in current main.


I agree with @pld here. I do not think the renaming of the internal packages is really necessary. The quest app can be renamed via it's flavor. Different apps can override the name as desired including the app Id.The app Id and versions are required for use in Playstore and typically the users aren't aware of them.

**Comment by ndegwamartin** [comment]
> > The main change I was interested in is the name of the APK that we generate as the generic APK, calling that OpenSRP vs Quest. For the internal code package names, I don't have a strong opinion on what that's called, I'm fine keeping it as it is in current main.
> 
> I agree with @pld here. I do not think the renaming of the internal packages is really necessary. The quest app can be renamed via it's flavor. Different apps can override the name as desired including the app Id.The app Id and versions are required for use in Playstore and typically the users aren't aware of them.

On _Playstore_ the app id is not entirely transparent to the users, e.g. in the link where one downloads the _Uber_ or _Whatsapp_ apps you do get signature therein - https://play.google.com/store/apps/details?id=com.ubercab and https://play.google.com/store/apps/details?id=com.whatsapp respectively. It is somewhat just a branding nuance though.

**Comment by pld** [comment]
so in our case wouldn't you get org.smartregister?

**Comment by ndegwamartin** [comment]
> so in our case wouldn't you get org.smartregister?

At the moment for generic quest we get `org.smartregister.fhircore.quest` but this PR changes that to `org.smartregister.fhircore.opensrp` 

If our conclusion is to remove the `fhircore` part then it will be `org.smartregister.opensrp` with the other flavors appending their unique project specific suffix e.g. `org.smartregister.opensrp.ecbis`. 

We could also have it be `org.smartregister.ecbis` but we'd loose the `opensrp`

**Comment by pld** [comment]
Ok I see that's a good justification to change, apologies, I didn't realize this. The below approach you suggested makes sense to me.

> If our conclusion is to remove the `fhircore` part then it will be `org.smartregister.opensrp` with the other flavors appending their unique project specific suffix e.g. `org.smartregister.opensrp.ecbis`.

**Comment by ellykits** [comment]
:+1: LGTM

**Comment by pld** [comment]
Yeah sure let's wait on the new pr until we can chat about package strategy a final time

**Pull request closed without merging**
