### PR TITLE
Fixing trailing commas issues on rule statuses

### PR DESCRIPTION
**Pull request by aurangzaibumer**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by aurangzaibumer** [comment]
@ellykits please review, can I start working on unit test cases?

**Review by pld — CHANGES_REQUESTED** [review]
please add some tests for joinToString

**Comment by aurangzaibumer** [comment]
> please add some tests for joinToString

done.

**Review by pld — DISMISSED** [review]
lgtm!

**Review by ellykits — CHANGES_REQUESTED** [review]
Can you resolve the failing CI build? Maybe re-run CI?

**Comment by ellykits** [comment]
Implementation and tests look good just need to verify that the CI will build correctly before we merge.

**Pull request merged**
