### PR TITLE
Enhance Insight Screen UX

### LINKED ISSUE #3194: Enhance Insights screen UX
**Describe the feature request.**
Following the feature impelmentation here: [#2873](https://github.com/opensrp/fhircore/pull/2873) , the right now when there are no **Unsynced Resources** the section just disappears. We can improve the UX by still showing the section but then showing a message like - **All resources synced** :heavy_check_mark:

**Additional context**
Screenshot of current state

When all the data is synced

When we have unsynced data

**Acceptance criteria**

- [ ] When there are no Unsynced resources there should be a message that shows **_No resources to sync_** or **_All resources synced_**

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Settings_
4. Click on _Insights_

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

### PR DESCRIPTION
**Pull request by Raynafs**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #3194

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by Raynafs** [comment]
Image showing the implementation when the username is null. This case applies to even when the others return null. They will show -

image

**Comment by Raynafs** [comment]
image
Possible implementation of all resources synced.

**Comment by Raynafs** [comment]
Video showing when all resources are synced and when we have unsynced resources 

[Screencast from 26-04-2024 08:54:34 ASUBUHI.webm](https://github.com/opensrp/fhircore/assets/110402503/e22f816c-4d3a-414f-ad3b-fb103d443461)

**Comment by ellykits** [comment]
Merging this. More UI tests can be added once instrumentation tests are re-activated to run on CI. For now the updated tests will suffice.

**Pull request merged**
