### PR TITLE
Sonarqube Workflow Configuration

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

SonarQube integration for the static analysis of code quality

**Engineer Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by pld** [comment]
@ndegwamartin is there a place/way to see the results of the check presented? Also there's this warning/error from the run, not sure if it matters

```
Unable to import Android Lint report file(s):
- /home/runner/work/fhircore/fhircore/android/quest/build/reports/lint-results-questDebug.xml
The report file(s) can not be found. Check that the property 'sonar.androidLint.reportPaths' is correctly configured.
```

**Comment by ndegwamartin** [comment]
@pld yeah the results are currently available via the portal of the internally deployed SonarQube instance. I can share the dets via DM . The idea is to have the reports exported and available on an instance of DefectDojo for efficiency in management.

Additionally, it is possible to have SonarQube decorate the PR with the vulnerabilities found per PR but we probably don't want those public until we fix them cc @bonfaceshisakha

**Comment by ndegwamartin** [comment]
> @ndegwamartin is there a place/way to see the results of the check presented? Also there's this warning/error from the run, not sure if it matters
> 
> ```
> Unable to import Android Lint report file(s):
> - /home/runner/work/fhircore/fhircore/android/quest/build/reports/lint-results-questDebug.xml
> The report file(s) can not be found. Check that the property 'sonar.androidLint.reportPaths' is correctly configured.
> ```

Looks like it might be picking the file path of the wrong variant, we can set that explicitly in [the gradle properties file](https://github.com/opensrp/fhircore/blob/a683b107671ed724a17cf4b765d83631ae2b9ec6/android/quest/build.gradle#L15) once we determine what the correct one is. Probably `lint-results-questRelease.xml`

Also note, since it is a _Warning_ level log it could be one of the paths that was tried and failed but eventually got the correct one.

**Comment by pld** [comment]
yea true true, if the results are coming through, this doesn't really matter, we can revisit it after the kts conversion pr is merged AND it's actually problem

**Pull request merged**
