### PR TITLE
Add Visibility configuration to views

### LINKED ISSUE #2041: [Configuration] Update all the configurable views to add a visibility configuration
**Description of feature**
- We will often have the need to show or hide views based on the patient data. Adding a visibility attribute on the configs will allow the configuration author to easily hide or show the views based on some rules that evaluate to `true` or `false` 

**Implementation**
- [x] Add a `visible` attribute to all the views we have for the configurable UI. Below is a list of the views
     - [ ] CARD, COLUMN, COMPOUND_TEXT, SPACER, PERSONAL_DATA, BUTTON
- [x] This attribute show should the view if its value is `true` and hide the view if its value is `false`
     - [ ]`true` should set the visibility to `visible` 
     - [ ] `false` should set the visibility to `gone` 

**Acceptance criteria**
- [x] It should be possible to toggle visibility for all configurable views.

### PR DESCRIPTION
**Pull request by DebbieArita**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2041  

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by SebaMutuku — CHANGES_REQUESTED** [review]
@DebbieArita I think you can update a sample config `json` to test this implementation on affected widgets' documentation.

**Comment by DebbieArita** [comment]
> @DebbieArita I think you can update a sample config `json` to test this implementation on affected widgets' documentation.

Sure @SebaMutuku. I'll have that on a different PR just so I can merge this one ASAP.

**Review by ellykits — CHANGES_REQUESTED** [review]
Apply the visibility check above this line [ViewRenderer#L52](https://github.com/opensrp/fhircore/blob/1906e7e0fb87888bb28c4e020401400fc3d4755c/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/ViewRenderer.kt#L52) as discussed

**Comment by DebbieArita** [comment]
> Apply the visibility check above this line [ViewRenderer#L52](https://github.com/opensrp/fhircore/blob/1906e7e0fb87888bb28c4e020401400fc3d4755c/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/ViewRenderer.kt#L52) as discussed

Closing this for the ViewRender approach implemented on https://github.com/opensrp/fhircore/pull/2052.

**Pull request closed without merging**
