### PR TITLE
196 | Risk assessment capture and flagging feature

### LINKED ISSUE #196: Add risk assessment questionnaire in Covax app
Enable segmenting users by “at-risk” and “not at risk” for severe illness from COVID-19. The at-risk group includes:
1. Over the age of 65
2. People with medical conditions such as cancer, HIV, obesity, or diabetes.

For this, we shall need to explore the usage of RiskAssessment FHIR resource https://www.hl7.org/fhir/riskassessment.html 
This resource can be used to represent the results of formal scoring/decision support tools that evaluate risk. It can also be used to capture a practitioner's subjective assessment of the patient's risk based on existing knowledge and previous experience.

After that, we shall need to have the risk parameter ranges that will be used in the validation/measure functionality to flag risk from a range of predefined risk factors i.e patient's age, disposition/ suffering from cancer, HIV, obesity, or diabetes etc. 

Sample [Riskassessment-example.json](https://www.hl7.org/fhir/riskassessment-example.json.html)

Subtasks (To be created as separate issues)
- [x] Add comorbidity questions (multi-select - boolean values)  to registration form similar to this https://ucc.uhcitp.in/
- [x] Add ‘at risk’ designation to a client record
- [x] Show notification on the registration form if the user is at risk
- [x] Display at risk flag on the list view
- [x] Display at risk flag on client profile
- [x] Update risk status post-registration if criteria are met

Detailed user story can be referenced [here](https://docs.google.com/document/d/1jD9PS5v6RcrVQZLLa90wrYBwWUckqxa_ibbWGbz7C-k/edit#heading=h.tteilzb7txx7)

Designs attached [here](https://www.figma.com/file/Ck46ofqC6kE6ISBC2YmwiI/COVID19-FHIR?node-id=880%3A1)

### PR DESCRIPTION
**Pull request by maimoonak**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #196 

**Type**
Choose one: (Feature) 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — COMMENTED** [review]
Reading through this, can you clarify how we're attaching the Flag resource to a Patient?

It seems like we're using an extension on the Patient resource, but from the Flag definition we can use the Flag's subject field to point to the Patient the flag is associated with.

**Comment by maimoonak** [comment]
> Reading through this, can you clarify how we're attaching the Flag resource to a Patient?
> 
> It seems like we're using an extension on the Patient resource, but from the Flag definition we can use the Flag's subject field to point to the Patient the flag is associated with.

Yeah we are adding this as extension. This was one of the requirements in #196 . 
We could have done it by adding a flag resource but then it is a separate resource and does not sync with Patient automatically. But yeah here I see that we can not add filter/authz on sync if needed for sensitive flags. Righnow the syncing of flag was the caveat.

**Comment by pld** [comment]
> > Reading through this, can you clarify how we're attaching the Flag resource to a Patient?
> > It seems like we're using an extension on the Patient resource, but from the Flag definition we can use the Flag's subject field to point to the Patient the flag is associated with.
> 
> Yeah we are adding this as extension. This was one of the requirements in #196 .
> We could have done it by adding a flag resource but then it is a separate resource and does not sync with Patient automatically. But yeah here I see that we can not add filter/authz on sync if needed for sensitive flags. Righnow the syncing of flag was the caveat.

OK I see, can you please create a new issue to change this from an extension to a link to the Flag resource and resolve the syncing issue?

This is low priority and we can address it the next time we touch these code paths or before we begin anything that depends on this.

**Comment by maimoonak** [comment]
https://github.com/opensrp/fhircore/issues/389 has been added to log all improvements identified

**Review by pld — APPROVED** [review]

**Pull request merged**
