### PR TITLE
Temporarily Disable Caching for MLS demo Hotfix

### LINKED ISSUE #2827: [FHIR Core] App should refresh and reload content based on the selected language from settings page
Currently, you need to manually reload the app i.e close to the background and relaunch to have the content translated to a new language

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #2827

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by f-odhiambo — APPROVED** [review]
Ready for merge :slightly_smiling_face:

**Comment by pld** [comment]
it seems like the longer term fix is to clear the cache when the language is changed, is that correct?

**Comment by ndegwamartin** [comment]
> it seems like the longer term fix is to clear the cache when the language is changed, is that correct?

Thoughts were around caching the configurations by locale. That way is if the user switches back and forth all available and previously interacted with language views are available on the cache.

**Comment by ellykits** [comment]
> it seems like the longer term fix is to clear the cache when the language is changed, is that correct?

We'll apply this for now @ndegwamartin

**Review by pld — APPROVED** [review]

**Pull request merged**
