### PR TITLE
Add register & profile performance profiling, disable jobs and allow dismissing loader view

### PR DESCRIPTION
**Pull request by ekigamba**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] or Closes #[issue number]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ekigamba** [comment]
@ellykits Here is the code for profiling

Attached is the data set that should be loaded with `app/debug` since this allows the app to load resources from local configs

[resources.zip](https://github.com/opensrp/fhircore/files/11480835/resources.zip)


Make sure to run 
```
CREATE INDEX IF NOT EXISTS `index_DateTimeIndexEntity_index_from` ON `DateTimeIndexEntity` (`index_from`)
``` 

on the database before copying it onto the device to replace the current one

**Review by pld — COMMENTED** [review]
can we make this configurable with a debug or a new profile flag and get this merged in?

**Comment by pld** [comment]
> can we make this configurable with a debug or a new profile flag and get this merged in?

the commented jobs that is

**Comment by ellykits** [comment]
@pld We are considering writing benchmarks for specific areas of code using [Jetpack Microbenchmark library](https://developer.android.com/topic/performance/benchmarking/microbenchmark-overview). After the kotlin DSL migration PR is merged and dependencies upgraded. Closing this PR (was used while measuring register/profile) data load performance - currently being undertaken by the QA team.

cc: @ekigamba

**Pull request closed without merging**
