### PR TITLE
Add Group.Characteristic model support in StructureMaps extraction

### PR DESCRIPTION
**Pull request by ekigamba**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] 

**Checklist**
- [x] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [x] I have added any strings visible on UI components to the `strings.xml` file
- [x] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [x] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [x] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Review by pld — DISMISSED** [review]
Cool, can you provide some context, why is this here and not in the sdk?

**Comment by ekigamba** [comment]
It's a optional param on the SDK. I don't remember clearly, but the SDK team prefers that some of these functionalities are not built into the SDK. 

They are currently thinking of removing the StructureMap-based extraction code from the SDK as an option https://github.com/google/android-fhir/issues/1366#issuecomment-1134952147

**Comment by pld** [comment]
Ok thanks, yeah if we have to maintain these types of extensions then I see the argument for why have it in the SDK at all.

The other side of the argument might be on uniformity of approach to structuremaps across implements of the SDK that use them, but we might need code like this in the SDK for that to be meaningful.

**Comment by pld** [comment]
I'm also wondering if there's a way to generate those types, this feels ad hoc

**Comment by ekigamba** [comment]
> I'm also wondering if there's a way to generate those types, this feels ad hoc

I believe there should be a better way to do this. We can possibly create an issue for this since the adoption is increasing and the effort for implementing the code generation for this is. However, we'll also need to provide the missing documentation for these models because the names are only found inside the JSON model schemas. On the FHIR documentation, these models are termed as `BackboneElement` only.

We can merge this in and create another issue to discuss and implement the dynamic code generation for this

cc @Rkareko

**Comment by ekigamba** [comment]
> Ok thanks, yeah if we have to maintain these types of extensions then I see the argument for why have it in the SDK at all.
> 
> The other side of the argument might be on uniformity of approach to structuremaps across implements of the SDK that use them, but we might need code like this in the SDK for that to be meaningful.

We can include this as a task on the issue so that we can propose and/or discuss with the SDK team on this

cc @Rkareko

**Review by Rkareko — APPROVED** [review]

**Comment by ekigamba** [comment]
The link to the issue is here @pld @Rkareko

**Pull request merged**
