### PR TITLE
passing empty bundle instead of null to trigger the careplan when we don't have any bundle resource

### PR DESCRIPTION
**Pull request by owais-vd**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #[issue number] or Closes #[issue number]

**Engineer Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the FHIRCore app to verify my change fixes the issue and/or does not break the app 
- [ ] I have checked that this PR does NOT introduce **breaking changes** that require an update to **_Content_** and/or **_Configs_**? _If it does add a sample here or a link to exactly what changes need to be made to the content._

**Code Reviewer Checklist**
- [ ] I have verified **Unit tests** have been written for any new feature(s) and edge cases
- [ ] I have verified any strings visible on UI components are in the `strings.xml` file
- [ ] I have verifed the [CHANGELOG.md](./CHANGELOG.md) file has any notable changes to the codebase
- [ ] I have verified the solution has been implemented in a configurable and generic way for reuseable components
- [ ] I have built and run the FHIRCore app to verify the change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by ellykits** [comment]
Just noticed this PR is pointing to opensrp.0.2.5 and does not include the questionnaire code refactor. Why do we need to trigger CarePlan generation @owais-vd when the bundle is null (meaning no extraction was performed)?  Is there as scenario like this?

**Comment by owais-vd** [comment]
yes @ellykits, a bundle is required only the first time when we generate a Careplan but in a Tasking-on-demand system we need to generate a second task, based on the submission of the first task so, in the second task case, we don't need to generate or init a Careplan we just need to generate a task and attached it to the previously generated Careplan. Therefore, at that moment we don't have a bundle or we don't require a bundle. cc: @dubdabasoduba

**Comment by ellykits** [comment]
Can you test and create another PR pointing to main branch?

**Comment by owais-vd** [comment]
https://github.com/opensrp/fhircore/pull/2432 previously did

**Comment by owais-vd** [comment]
@ellykits implementation has changed, and now we don't need this PR anymore can safely close this

**Pull request closed without merging**
