### PR TITLE
Hide immunization card for patients over 5yrs

### PR DESCRIPTION
**Pull request by DebbieArita**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #https://github.com/opensrp/fhir-resources/issues/814

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by dubdabasoduba** [comment]
@DebbieArita I tested this and it works well. I will however create and issue to figure out why the view renderer does not pass the visible attribute as expected.

cc: @ellykits

**Comment by DebbieArita** [comment]
> @DebbieArita I tested this and it works well. I will however create and issue to figure out why the view renderer does not pass the visible attribute as expected.
> 
> cc: @ellykits

We managed to resolve this... @dubdabasoduba

**Review by pld — CHANGES_REQUESTED** [review]
can you please add a test for the new conditional on child isVisible?

**Comment by dubdabasoduba** [comment]
@DebbieArita Please add another PR targeting the release branch.

**Pull request merged**
