### PR TITLE
WIP | CQL evaluator with G6PD library

### LINKED ISSUE #731: Quest/G6PD  - Test CQL statement on CQLEvaluator module and document findings
- [x] Check out the implementation of the CQLEvaluatorSample app and see if we can tweak the Library of resources to suit our use case 
- [x] Document the findings of the RnD
- [x] Modify the library of resources to mimic the G6PD use case 
- [x] Run and test the  CQL statement  for G6PD Threshold management

### PR DESCRIPTION
**Pull request by maimoonak**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #731 

**Type**
Choose one: (Bug fix | Feature | Documentation | Testing | Code health | Release | Other) 

**Checklist**
- [ ] I have written **Unit tests** for any new feature(s) and edge cases for bug fixes
- [ ] I have added any strings visible on UI components to the `strings.xml` file
- [ ] I have updated the  [CHANGELOG.md](./CHANGELOG.md) file for any notable changes to the codebase
- [ ] I have run `./gradlew spotlessApply` and `./gradlew spotlessCheck` to check my code follows the project's style guide
- [ ] I have built and run the fhircore app to verify my change fixes the issue and/or does not break the app

### CODE REVIEW

**Comment by pld** [comment]
Cool, so there's nothing g6pd specific about that correct? This is about running CQL post questionnaire response structure map application, and the g6pd specific CQL is defined on HAPI not in code

**Comment by maimoonak** [comment]
Yes. The CQL is pulled from server and run. Whatever it is it would be executed irrespective of content. Plz note that in this PR the library 4575 runs g6pd cql. if it is updated to run anc cql it would do so.

**Comment by pld** [comment]
OK so it is hard coded? We will have to refactor this to use CQL defined in a Composition after the pre-req work there is complete.

But that sounds good for now, thank you

**Comment by maimoonak** [comment]
#865 handled and added the needed functionality

**Pull request closed without merging**
