### PR TITLE
OpenSRP 0.2.5 v1

### PR DESCRIPTION
**Pull request by ndegwamartin**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes https://github.com/onaio/fhir-resources/issues/2531

### CODE REVIEW

**Review by dubdabasoduba — APPROVED** [review]
@ndegwamartin This works to reduce the number of resources to update. We can maybe update it further to target the specific Tasks created from the extraction.

**Comment by ndegwamartin** [comment]
> @ndegwamartin This works to reduce the number of resources to update. We can maybe update it further to target the specific Tasks created from the extraction.

@dubdabasoduba Yeah we can do that. Is the performance acceptable for the release so that we can track it on a separate ticket or would the update be a significant performance upgrade? Also wouldn't we want to have all the users tasks updated in real time for the current patient of interest?

**Comment by dubdabasoduba** [comment]
> > @ndegwamartin This works to reduce the number of resources to update. We can maybe update it further to target the specific Tasks created from the extraction.
> 
> @dubdabasoduba Yeah we can do that. Is the performance acceptable for the release so that we can track it on a separate ticket or would the update be a significant performance upgrade? Also wouldn't we want to have all the users tasks updated in real time for the current patient of interest?

It's definitely going to reduce the number of tasks evaluated further. The workflow with the highest number of Tasks has 60. The one that follows has 10 tasks. Which means if you are performing any other workflow you are going to have less than 10 tasks to evaluate

**Comment by dubdabasoduba** [comment]
> > > @ndegwamartin This works to reduce the number of resources to update. We can maybe update it further to target the specific Tasks created from the extraction.
> > 
> > 
> > @dubdabasoduba Yeah we can do that. Is the performance acceptable for the release so that we can track it on a separate ticket or would the update be a significant performance upgrade? Also wouldn't we want to have all the users tasks updated in real time for the current patient of interest?
> 
> It's definitely going to reduce the number of tasks evaluated further. The workflow with the highest number of Tasks has 60+. The one that follows has 10 tasks. This means if you are performing any other workflow you are going to have less than 10 tasks to evaluate

**Review by dubdabasoduba — APPROVED** [review]

**Comment by ndegwamartin** [comment]
> > @dubdabasoduba Yeah we can do that. Is the performance acceptable for the release so that we can track it on a separate ticket or would the update be a significant performance upgrade? Also wouldn't we want to have all the users tasks updated in real time for the current patient of interest?
> 
> It's definitely going to reduce the number of tasks evaluated further. The workflow with the highest number of Tasks has 60+. The one that follows has 10 tasks. This means if you are performing any other workflow you are going to have less than 10 tasks to evaluate
> 
> As agreed let's make the update on the PR to `main`

Actually the 70+ tasks per submission feels like a significant number. My understanding was that they'd always be less than 10 during the evaluation. The LOE might be small, let me see

**Review by dubdabasoduba — APPROVED** [review]

**Pull request merged**
